<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>Tweet Away</title>
    <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
    <style>
        body {
            margin: 50px 0 0 0;
            padding: 0;
            width: 100%;
            font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
            text-align: center;
            color: #aaa;
            font-size: 18px;
        }
        h1 {
            color: #719e40;
            letter-spacing: -3px;
            font-family: 'Lato', sans-serif;
            font-size: 100px;
            font-weight: 200;
            margin-bottom: 0;
        }
        tr, td {
            text-align:left;
        }

    </style>
</head>
<body>
<img src="../public/tweetaway.png" height="220" width="260"/>
<h1>Tweet Away</h1>
<div>A web social media application to waste away time!</div><br>
<div>
    <form action = "/feed/add" method = "POST">
        User:<input type="text" name="username" id="username" style="width: 10%;">
        Message:<input type="text" name="message" id="message" maxlength="248" style="width: 60%;">
        <input type="submit" id="submit" value="Submit"><br>
    </form>
</div>
<div>
    <br>
    <table>
    <tr><th>User</th><th>Time</th><th>Message</th></tr>

    <?php
    $style = "style='text-align:left;'";
    foreach ($args['feed'] as $row){
        echo "<tr>";
        echo "<td>".$row['name']."</td>";
        echo "<td>".$row['time']."</td>";
        echo "<td><p>".$row['message']."</p></td>";
        echo "</tr>";
    }

    ?>
    </table>
</div>

<div>
    <table id="feedTable">
        <tr><th>User</th><th>Time</th><th>Message</th></tr>

    </table>
</div>
<?php if (isset($name)) : ?>
    <h2>Hello <?= htmlspecialchars($name); ?>!</h2>
<?php endif; ?>

</body>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="main.js"></script>
</html>