<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>Tweet Away</title>
    <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
    <style>
        body {
            margin: 50px 0 0 0;
            padding: 0;
            width: 100%;
            font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
            text-align: center;
            color: #aaa;
            font-size: 18px;
        }

        h1 {
            color: #719e40;
            letter-spacing: -3px;
            font-family: 'Lato', sans-serif;
            font-size: 100px;
            font-weight: 200;
            margin-bottom: 0;
        }

        tr, td {
            text-align: left;
        }

    </style>
</head>
<body>
<img src="../public/tweetaway.png" height="220" width="260"/>
<h1>Tweet Away</h1>
<div>A web social media application to waste away time!</div>
<br>
<div>
    User:<input type="text" name="username" id="username" style="width: 10%;">
    Message:<input type="text" name="message" id="message" maxlength="248" style="width: 60%;">
    <button id="add-feed">Add Post</button><br><br>
</div>
<div>
    <table id="feedTable">
    </table>
</div>
<?php if (isset($name)) : ?>
    <h2>Hello <?= htmlspecialchars($name); ?>!</h2>
<?php endif; ?>

</body>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script>
    $(document).ready(function () {

        var $feedTable = $('#feedTable');
        var $username = $('#username');
        var $message = $('#message');
        $.ajax({
            type: 'GET',
            url: '/feed',
            success: function ($Data) {
                $.each(JSON.parse($Data), function (i, feedItem) {
                    $feedTable.append('<tr><th>' + feedItem.name + '</th><th>' + feedItem.time + '</th><th>' + feedItem.message + '</th></tr>');
                });
            },
            error: function () {
                alert('error loading feed');
            }
        });

        $('#add-feed').on('click', function () {
            var feed = {
                username: $username.val(),
                message: $message.val(),
            };
            $.ajax({
                type: 'POST',
                url: '/feed/add',
                data: feed,
                success: function ($newFeed) {
                    var parseFeed = JSON.parse($newFeed);
                    $feedTable.prepend('<tr><th>' + parseFeed.name + '</th><th>' + parseFeed.time + '</th><th>' + parseFeed.message + '</th></tr>');

                },
                error: function () {
                    alert('error adding feed');
                }
            });
        });

    });
</script>
</html>